version: '3.7'
services:
  neo4j:
    image: neo4j
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_dbms_logs_debug_level: DEBUG