{
	"email": "heitorab@usp.br",
	"nome": "Heitor Augusto Barbosa",
	"ue": "FEA",
	"total_avaliacoes": 5,
	"media_avaliacoes": 6,
},
{
	"email": "arthursc@usp.br",
	"nome": "Arthur Souza Campos",
	"ue": "FAU",
	"total_avaliacoes": 8,
	"media_avaliacoes": 7.5,
},
{
	"email": "angelicamaria_22@usp.br",
	"nome": "Angelica Maria de Albuquerque",
	"ue": "IME",
	"total_avaliacoes": 2,
	"media_avaliacoes": 9.2,
},
{
	"email": "anaborges-d@usp.br",
	"nome": "Ana Borges Dias",
	"ue": "FFLCH",
	"total_avaliacoes": 0,
},
{
	"email": "gabriel_ferro@usp.br",
	"nome": "Gabriel Duarte Ferro",
	"ue": "ICB",
	"total_avaliacoes": 2,
	"media_avaliacoes": 6,
},
{
	"email": "luisa_gl12@usp.br",
	"nome": "Luísa Gomes Lima",
	"ue": "IME",
	"total_avaliacoes": 20,
	"media_avaliacoes": 6.8,
},
{
	"email": "fmm@usp.br",
	"nome": "Felipe Monteiro Martins",
	"ue": "FEA",
	"total_avaliacoes": 0,
},
{
	"email": "bruna-pm15@usp.br",
	"nome": "Bruna Pereira Moura",
	"ue": "IO",
	"total_avaliacoes": 35,
	"media_avaliacoes": 7.8,
},